
import com.mycompany.projetopi2semestre2.ProcurarCliente;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author carlos silva lopes
 */
public class teste extends javax.swing.JFrame {

    /**
     * Creates new form teste
     */
    public teste() {
        initComponents();
        CBTESTE.selectWithKeyChar(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNomes = new javax.swing.JTable();
        jctipo = new javax.swing.JComboBox<>();
        txtNomeBuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblNomes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cliente", "CPF", "DataNascimento", "EstadoCivil", "Email", "Sexo", "Telefone", "CEP", "Endereco", "Numero", "Complemento"
            }
        ));
        jScrollPane1.setViewportView(tblNomes);

        jctipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "CPF" }));

        txtNomeBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeBuscarKeyReleased(evt);
            }
        });

        jButton1.setText("Buscar");

        jButton2.setText("Deletar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jctipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jButton2)))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jctipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(424, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeBuscarKeyReleased
 String tipo = "";
        String escolha = jctipo.getSelectedItem().toString().trim();
        if (escolha.equals("Nome")) {
            tipo = " " + "nomeCliente";
        }
        if (escolha.equals("CPF")) {
            tipo = " " + "cpfCliente";
        }
        String arg = txtNomeBuscar.getText();

        DefaultTableModel modeloO = (DefaultTableModel) tblNomes.getModel();
        int l = modeloO.getRowCount();

        if (l > 0) {
            while (1 > 0) {
                ((DefaultTableModel) tblNomes.getModel()).removeRow(l - 1);
            }

        }
        try {
            ResultSet rs = ClienteDAO.carregaTabela(tipo, arg);

            DefaultTableModel mp = (DefaultTableModel) tblNomes.getModel();

            while (rs.next()) {
                String Coluna0 = rs.getString("idCliente").trim();
                String Coluna1 = rs.getString("nomeCliente").trim();
                String Coluna2 = rs.getString("cpfCliente").trim();
                String Coluna3 = rs.getDate("dataNascimento").toString();
                String Coluna4 = rs.getString("EstadoCliente").trim();
                String Coluna5 = rs.getString("emailCliente").trim();
                String Coluna6 = rs.getString("sexoCliente").trim();
                String Coluna7 = rs.getString("telefoneCliente").trim();
                String Coluna8 = rs.getString("cepCliente").trim();
                String Coluna9 = rs.getString("enderecoCliente").trim();
                String Coluna10 = rs.getString("numeroEndCliente").trim();
                String Coluna11 = rs.getString("complementoCliente").trim();

                mp.addRow(new String[]{Coluna0, Coluna1, Coluna2, Coluna3, Coluna4, Coluna5, Coluna6, Coluna7, Coluna8, Coluna9, Coluna10, Coluna11});
            }

        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(this, "ocorreu um erro " + erro);
            System.out.println(erro);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ProcurarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }        }    }//GEN-LAST:event_txtNomeBuscarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jctipo;
    private javax.swing.JTable tblNomes;
    private javax.swing.JTextField txtNomeBuscar;
    // End of variables declaration//GEN-END:variables
}
